all:
  children:
    gitlab_hosts:
      hosts:
        gitlab01:
          ansible_host: 127.0.0.1
          ansible_port: 2206
          ansible_user: vagrant
          ansible_ssh_private_key_file: /Users/gabriel.carmo/projetos/github/gitlab-traefik/vagrant/.vagrant/machines/gitlab-traefik/virtualbox/private_key
    vagrant_host:
      hosts:
        localhost:
          ansible_connection: local
